
    create table address (
       id int4 generated by default as identity,
        complement varchar(255),
        neighborhood varchar(255),
        number varchar(255),
        public_place varchar(255),
        zip_code varchar(255),
        city_id int4,
        customer_id int4,
        primary key (id)
    );

    create table barcode_payment (
       due_date timestamp,
        payday timestamp,
        purchase_id int4 not null,
        primary key (purchase_id)
    );

    create table card_payment (
       number_installments int4,
        purchase_id int4 not null,
        primary key (purchase_id)
    );

    create table category (
       id int4 generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table city (
       id int4 generated by default as identity,
        name varchar(255),
        state_id int4,
        primary key (id)
    );

    create table customer (
       id int4 generated by default as identity,
        cpf_or_cnpj varchar(255),
        email varchar(255),
        name varchar(255),
        type int4,
        primary key (id)
    );

    create table payment (
       purchase_id int4 not null,
        status int4,
        primary key (purchase_id)
    );

    create table phone (
       customer_id int4 not null,
        phones varchar(255)
    );

    create table product (
       id int4 generated by default as identity,
        name varchar(255),
        price float8,
        primary key (id)
    );

    create table product_category (
       product_id int4 not null,
        category_id int4 not null
    );

    create table purchase (
       id int4 generated by default as identity,
        instant timestamp,
        customer_id int4,
        delivery_address_id int4,
        primary key (id)
    );

    create table purchase_item (
       discount float8,
        price float8,
        quantity int4,
        purchase_id int4 not null,
        product_id int4 not null,
        primary key (product_id, purchase_id)
    );

    create table state (
       id int4 generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    alter table if exists customer 
       add constraint UK_dwk6cx0afu8bs9o4t536v1j5v unique (email);

    alter table if exists address 
       add constraint FKpo044ng5x4gynb291cv24vtea 
       foreign key (city_id) 
       references city;

    alter table if exists address 
       add constraint FK93c3js0e22ll1xlu21nvrhqgg 
       foreign key (customer_id) 
       references customer;

    alter table if exists barcode_payment 
       add constraint FK4njb0tn2jkoa5bunsnpcu970f 
       foreign key (purchase_id) 
       references payment;

    alter table if exists card_payment 
       add constraint FK7dq1lkv5o17qj7wcaa896m76r 
       foreign key (purchase_id) 
       references payment;

    alter table if exists city 
       add constraint FK6p2u50v8fg2y0js6djc6xanit 
       foreign key (state_id) 
       references state;

    alter table if exists payment 
       add constraint FKmm2h9p8cpu4741lwxyn2fnpgg 
       foreign key (purchase_id) 
       references purchase;

    alter table if exists phone 
       add constraint FKgvgc4f2c3qkiswyv6bbs0br1p 
       foreign key (customer_id) 
       references customer;

    alter table if exists product_category 
       add constraint FKkud35ls1d40wpjb5htpp14q4e 
       foreign key (category_id) 
       references category;

    alter table if exists product_category 
       add constraint FK2k3smhbruedlcrvu6clued06x 
       foreign key (product_id) 
       references product;

    alter table if exists purchase 
       add constraint FK2pehe23hwdcyql94c531rbf70 
       foreign key (customer_id) 
       references customer;

    alter table if exists purchase 
       add constraint FKhu8d8vuae33k8op7ssujvlj36 
       foreign key (delivery_address_id) 
       references address;

    alter table if exists purchase_item 
       add constraint FK1mncc5yaore1sibgpj3jc4a7u 
       foreign key (purchase_id) 
       references purchase;

    alter table if exists purchase_item 
       add constraint FKq69apam78dbi0cggl37ge6auf 
       foreign key (product_id) 
       references product;

    create table address (
       id int4 generated by default as identity,
        complement varchar(255),
        neighborhood varchar(255),
        number varchar(255),
        public_place varchar(255),
        zip_code varchar(255),
        city_id int4,
        customer_id int4,
        primary key (id)
    );

    create table barcode_payment (
       due_date timestamp,
        payday timestamp,
        purchase_id int4 not null,
        primary key (purchase_id)
    );

    create table card_payment (
       number_installments int4,
        purchase_id int4 not null,
        primary key (purchase_id)
    );

    create table category (
       id int4 generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table city (
       id int4 generated by default as identity,
        name varchar(255),
        state_id int4,
        primary key (id)
    );

    create table customer (
       id int4 generated by default as identity,
        cpf_or_cnpj varchar(255),
        email varchar(255),
        name varchar(255),
        type int4,
        primary key (id)
    );

    create table payment (
       purchase_id int4 not null,
        status int4,
        primary key (purchase_id)
    );

    create table phone (
       customer_id int4 not null,
        phones varchar(255)
    );

    create table product (
       id int4 generated by default as identity,
        name varchar(255),
        price float8,
        primary key (id)
    );

    create table product_category (
       product_id int4 not null,
        category_id int4 not null
    );

    create table purchase (
       id int4 generated by default as identity,
        instant timestamp,
        customer_id int4,
        delivery_address_id int4,
        primary key (id)
    );

    create table purchase_item (
       discount float8,
        price float8,
        quantity int4,
        purchase_id int4 not null,
        product_id int4 not null,
        primary key (product_id, purchase_id)
    );

    create table state (
       id int4 generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    alter table if exists customer 
       add constraint UK_dwk6cx0afu8bs9o4t536v1j5v unique (email);

    alter table if exists address 
       add constraint FKpo044ng5x4gynb291cv24vtea 
       foreign key (city_id) 
       references city;

    alter table if exists address 
       add constraint FK93c3js0e22ll1xlu21nvrhqgg 
       foreign key (customer_id) 
       references customer;

    alter table if exists barcode_payment 
       add constraint FK4njb0tn2jkoa5bunsnpcu970f 
       foreign key (purchase_id) 
       references payment;

    alter table if exists card_payment 
       add constraint FK7dq1lkv5o17qj7wcaa896m76r 
       foreign key (purchase_id) 
       references payment;

    alter table if exists city 
       add constraint FK6p2u50v8fg2y0js6djc6xanit 
       foreign key (state_id) 
       references state;

    alter table if exists payment 
       add constraint FKmm2h9p8cpu4741lwxyn2fnpgg 
       foreign key (purchase_id) 
       references purchase;

    alter table if exists phone 
       add constraint FKgvgc4f2c3qkiswyv6bbs0br1p 
       foreign key (customer_id) 
       references customer;

    alter table if exists product_category 
       add constraint FKkud35ls1d40wpjb5htpp14q4e 
       foreign key (category_id) 
       references category;

    alter table if exists product_category 
       add constraint FK2k3smhbruedlcrvu6clued06x 
       foreign key (product_id) 
       references product;

    alter table if exists purchase 
       add constraint FK2pehe23hwdcyql94c531rbf70 
       foreign key (customer_id) 
       references customer;

    alter table if exists purchase 
       add constraint FKhu8d8vuae33k8op7ssujvlj36 
       foreign key (delivery_address_id) 
       references address;

    alter table if exists purchase_item 
       add constraint FK1mncc5yaore1sibgpj3jc4a7u 
       foreign key (purchase_id) 
       references purchase;

    alter table if exists purchase_item 
       add constraint FKq69apam78dbi0cggl37ge6auf 
       foreign key (product_id) 
       references product;
